// AUTO-GENERATED by scripts/dev/codegen-testids.sh � DO NOT EDIT BY HAND.
// Regenerate after any testID change in src/.
//
// Plan 4 T4.4.D. Provides string-literal types for testIDs
// so a Maestro flow author who types a non-existent ID gets
// a typecheck error at author time.

/**
 * Every static (literal-string) testID in src/.
 * Sorted alphabetically. Use as the type for any function that
 * accepts a testID argument from a flow author.
 */
export type StaticTestId =
  | 'add-todo-input' // src/components/AddTodoInput.tsx:33 (TextInput)
  | 'add-todo-row' // src/components/AddTodoInput.tsx:21 (View)
  | 'add-todo-submit' // src/components/AddTodoInput.tsx:41 (Pressable)
  | 'clear-completed' // src/components/FilterTabs.tsx:46 (Pressable)
  | 'empty-state' // src/components/EmptyState.tsx:16 (View)
  | 'error-boundary' // src/components/ErrorBoundary.tsx:61 (View)
  | 'error-boundary-retry' // src/components/ErrorBoundary.tsx:81 (Pressable)
  | 'filter-tabs' // src/components/FilterTabs.tsx:21 (View)
  | 'hydrating' // src/screens/HomeScreen.tsx:15 (View)
  | 'todo-header' // src/components/Header.tsx:9 (View)
  | 'todo-header-count' // src/components/Header.tsx:11 (Text)
  | 'todo-list'; // src/components/TodoList.tsx:26 (FlatList)

/**
 * Prefixes for dynamic testIDs (template-literal form, e.g.
 * `todo-item-${id}`). Use `testIdFor(prefix, id)` to build
 * the full ID at runtime.
 */
export type DynamicTestIdPrefix =
  | 'filter' // src/components/FilterTabs.tsx:33 flag="dynamic id: Maestro requires regex (id: 'prefix-')"
  | 'todo-checkbox' // src/components/TodoItem.tsx:61 flag="checkbox absorbs id (Maestro id-search may fail); inside Swipeable: tap-through unreliable from synthesized XCUITest; dynamic id: Maestro requires regex (id: 'prefix-')"
  | 'todo-delete' // src/components/TodoItem.tsx:38 flag="dynamic id: Maestro requires regex (id: 'prefix-')"
  | 'todo-item' // src/components/TodoItem.tsx:57 flag="checkbox absorbs id (Maestro id-search may fail); inside Swipeable: tap-through unreliable from synthesized XCUITest; dynamic id: Maestro requires regex (id: 'prefix-')"
  | 'todo-text'; // src/components/TodoItem.tsx:68 flag="dynamic id: Maestro requires regex (id: 'prefix-')"

/**
 * Build a testID from a known prefix + an id. Catches typos in
 * the prefix at typecheck time.
 */
export function testIdFor<P extends DynamicTestIdPrefix>(prefix: P, id: string): `${P}-${string}` {
  return `${prefix}-${id}` as `${P}-${string}`;
}

/**
 * Sentinel: any testID value (static or dynamic-prefix form).
 * Use as the type for an external (e.g. Maestro flow) consumer
 * that may receive either form.
 */
export type AnyTestId = StaticTestId | `${DynamicTestIdPrefix}-${string}`;
