#!/usr/bin/env bash
# codegen-testids.sh — generate `e2e/types/testids.d.ts` from inventory
#
# Plan 4 T4.4.D. Reads inventory-testids.sh JSON output and emits a
# TypeScript module with:
#   - A string-literal union of every literal testID in src/
#   - Helper `testIdFor(prefix, id)` for the dynamic-prefix patterns
#   - JSDoc comments noting the gotcha flag for each entry
#
# Future: a TS-typed Maestro flow builder consumes this module so
# flow authoring gets autocomplete and "rename testID in source →
# orphan reference in flow" fails typecheck.
#
# USAGE:
#   scripts/dev/codegen-testids.sh                    # write to default path
#   scripts/dev/codegen-testids.sh > some-other.d.ts  # stdout
#
# Wired into lefthook pre-commit on src/**/*.tsx so the generated
# file stays in sync with source. Generated output is committed to
# the repo (treat it as source-of-truth, not artifact).

set -eo pipefail

cd "$(dirname "$0")/../.."

OUT="${1:-e2e/types/testids.d.ts}"

if [ "$OUT" != "-" ]; then
  mkdir -p "$(dirname "$OUT")"
fi

INVENTORY=$(bash scripts/dev/inventory-testids.sh --json)

# Use python to format — readily available, handles edge cases in
# string escaping better than bash for this kind of templating.
GENERATED=$(python <<PY
import json
inv = json.loads('''$INVENTORY''')

literals = []  # static IDs like "empty-state"
dynamics = []  # template-literal IDs like "todo-item-\${id}"
for r in inv:
    tid = r['testID']
    if '\${' in tid:
        # Strip the dynamic part to get the prefix
        prefix = tid.split('\${')[0]
        dynamics.append((prefix.rstrip('-'), r))
    else:
        literals.append((tid, r))

literals.sort(key=lambda x: x[0])
dynamics.sort(key=lambda x: x[0])

print('// AUTO-GENERATED by scripts/dev/codegen-testids.sh — DO NOT EDIT BY HAND.')
print('// Regenerate after any testID change in src/.')
print('//')
print('// Plan 4 T4.4.D. Provides string-literal types for testIDs')
print('// so a Maestro flow author who types a non-existent ID gets')
print('// a typecheck error at author time.')
print('')
print('/**')
print(' * Every static (literal-string) testID in src/.')
print(' * Sorted alphabetically. Use as the type for any function that')
print(' * accepts a testID argument from a flow author.')
print(' */')
print('export type StaticTestId =')
for tid, r in literals:
    print(f'  | {json.dumps(tid)}  // {r["file"]}:{r["line"]} ({r["tag"]})')
print('  ;')
print('')
print('/**')
print(' * Prefixes for dynamic testIDs (template-literal form, e.g.')
print(' * \`todo-item-\${id}\`). Use \`testIdFor(prefix, id)\` to build')
print(' * the full ID at runtime.')
print(' */')
print('export type DynamicTestIdPrefix =')
for pfx, r in dynamics:
    flag = r['flag']
    print(f'  | {json.dumps(pfx)}  // {r["file"]}:{r["line"]} flag={json.dumps(flag)}')
print('  ;')
print('')
print('/**')
print(' * Build a testID from a known prefix + an id. Catches typos in')
print(' * the prefix at typecheck time.')
print(' */')
print('export function testIdFor<P extends DynamicTestIdPrefix>(')
print('  prefix: P,')
print('  id: string,')
print('): \`\${P}-\${string}\`')
print('{')
print('  return \`\${prefix}-\${id}\` as \`\${P}-\${string}\`;')
print('}')
print('')
print('/**')
print(' * Sentinel: any testID value (static or dynamic-prefix form).')
print(' * Use as the type for an external (e.g. Maestro flow) consumer')
print(' * that may receive either form.')
print(' */')
print('export type AnyTestId = StaticTestId | \`\${DynamicTestIdPrefix}-\${string}\`;')
PY
)

if [ "$OUT" = "-" ]; then
  printf '%s\n' "$GENERATED"
else
  printf '%s\n' "$GENERATED" > "$OUT"
  echo "✓ wrote $OUT ($(wc -l < "$OUT") lines)"
fi
