#!/usr/bin/env bash
# inventory-testids.sh — scan src/ for testIDs and flag Maestro gotchas
#
# WHY THIS EXISTS:
# Building tour.yaml took 8 explorer-cloud iterations because we wrote
# Maestro selectors blind. This script makes every testID's REAL
# accessibility behavior visible at author time, so the next flow
# author writes correct selectors on the first try.
#
# Each row in the output table answers: "if I write
# `tapOn: { id: <this testID> }` in a Maestro flow, will it work?"
# The `flag` column carries the answer.
#
# USAGE:
#   scripts/dev/inventory-testids.sh                # markdown to stdout
#   scripts/dev/inventory-testids.sh --json         # machine-readable
#   scripts/dev/inventory-testids.sh --strict       # exit 1 on any flag
#
# Pure bash + ripgrep (Windows git-bash safe). Run from any cwd.

set -eo pipefail

cd "$(dirname "$0")/../.."

format=markdown
strict=0
for arg in "$@"; do
  case "$arg" in
    --json) format=json ;;
    --strict) strict=1 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "::error::unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# Capture all `testID=` occurrences. Format: file:line:content
results=$(rg -n --no-heading 'testID=' src/ 2>/dev/null || true)
if [ -z "$results" ]; then
  echo "::warning::no testID= occurrences in src/" >&2
  exit 0
fi

flag_count=0
output=""
json_acc=""

while IFS=':' read -r file line content; do
  [ -z "$file" ] && continue
  # Normalize Windows backslashes from rg into forward slashes for display
  file_norm=$(printf '%s' "$file" | sed 's#\\#/#g')

  # Extract testID literal — handles both string `"foo"` and template `\`foo-${x}\`` forms
  raw_line=$(sed -n "${line}p" "$file") || raw_line=""
  testid=$(printf '%s\n' "$raw_line" | sed -n -E 's/.*testID="([^"]+)".*/\1/p')
  if [ -z "$testid" ]; then
    testid=$(printf '%s\n' "$raw_line" | sed -n -E 's/.*testID=\{`([^`]+)`\}.*/\1/p')
  fi
  [ -z "$testid" ] && testid="<unparseable>"

  # JSX opener: scan up to 12 lines back for `<Foo`. STOP at the
  # testID line — looking forward catches an unrelated child opener.
  start=$((line > 12 ? line - 12 : 1))
  window=$(sed -n "${start},${line}p" "$file" 2>/dev/null || echo "")
  tag=$(printf '%s\n' "$window" | grep -oE '<[A-Z][A-Za-z]+' | tail -1 | tr -d '<' || true)
  [ -z "$tag" ] && tag="?"

  # Wrapper: <Swipeable up to 50 lines back
  wstart=$((line > 50 ? line - 50 : 1))
  wrap_window=$(sed -n "${wstart},${line}p" "$file" 2>/dev/null || echo "")
  wrapper="-"
  if printf '%s\n' "$wrap_window" | grep -qE '<Swipeable\b'; then
    wrapper="Swipeable"
  fi

  # accessibilityRole on same element
  a11y_role=$(printf '%s\n' "$window" | grep -oE 'accessibilityRole="[^"]*"' | head -1 \
    | sed -E 's/accessibilityRole="([^"]*)"/\1/' || true)
  [ -z "$a11y_role" ] && a11y_role="-"

  # onPress on the element?
  has_onpress=0
  if printf '%s\n' "$window" | grep -qE '\bonPress(In|Out)?='; then
    has_onpress=1
  fi

  # Dynamic testID (template literal with ${...})
  is_dynamic=0
  case "$testid" in *'${'*) is_dynamic=1 ;; esac

  # Rules engine — concat flags with semicolons.
  flag_str=""
  add_flag() { if [ -z "$flag_str" ]; then flag_str="$1"; else flag_str="$flag_str; $1"; fi; }

  case "$a11y_role" in
    checkbox) add_flag "checkbox absorbs id (Maestro id-search may fail)" ;;
    radio|switch) add_flag "$a11y_role absorbs id (Maestro id-search may fail)" ;;
  esac
  if [ "$wrapper" = "Swipeable" ] && [ "$has_onpress" -gt 0 ]; then
    add_flag "inside Swipeable: tap-through unreliable from synthesized XCUITest"
  fi
  if [ "$is_dynamic" -eq 1 ]; then
    add_flag "dynamic id: Maestro requires regex (id: 'prefix-')"
  fi
  if [ "$tag" = "View" ] && [ "$has_onpress" -eq 0 ]; then
    add_flag "View+testID but no onPress: tap won't dismiss keyboard"
  fi
  if [ "$tag" = "TextInput" ]; then
    add_flag "TextInput: tap focuses + opens keyboard (remember hideKeyboard later)"
  fi

  if [ -z "$flag_str" ]; then
    flag_str="ok"
  else
    flag_count=$((flag_count + 1))
  fi

  loc="${file_norm}:${line}"
  output+="| \`${testid}\` | ${loc} | ${tag} | ${wrapper} | ${a11y_role} | ${flag_str} |"$'\n'
  json_acc+="    {\"testID\":\"${testid}\",\"file\":\"${file_norm}\",\"line\":${line},\"tag\":\"${tag}\",\"wrapper\":\"${wrapper}\",\"role\":\"${a11y_role}\",\"flag\":\"${flag_str}\"},"$'\n'
done <<< "$results"

if [ "$format" = "json" ]; then
  printf '['
  printf '\n%s' "${json_acc%,$'\n'}"
  printf '\n]\n'
else
  cat <<EOF
# testID inventory

_Generated by \`scripts/dev/inventory-testids.sh\` — scan of \`src/\`
with the rules engine that encodes the gotchas discovered across
8 explorer-cloud iterations._

| testID | location | element | wrapper | a11y role | flag |
| ------ | -------- | ------- | ------- | --------- | ---- |
EOF
  printf '%s' "$output"
  cat <<'EOF'

## Legend

- **flag = ok**: safe to use `tapOn: { id: <testID> }` directly
- **checkbox absorbs id**: iOS XCUITest collapses the row into a single
  accessibility element keyed on its label — Maestro can't match by id
  alone. Use `tapOn: { id: '<prefix>-', index: N }` or change the
  `accessibilityRole` if testability is the priority.
- **inside Swipeable**: gesture-handler's pan recognizer competes with
  synthesized taps. Tap-on-text rarely propagates to the parent
  Pressable's onPress. Use a flow that doesn't rely on tap-toggling
  the row, or target a distinct child.
- **dynamic id**: `testID={`foo-${x}`}` requires Maestro regex
  (`id: 'foo-'`); literal `id: 'foo-uuid'` won't work.
- **View+testID but no onPress**: useful for assertions but tapping a
  non-touchable View doesn't dismiss the keyboard. Use `- hideKeyboard`.
- **TextInput**: opens the soft keyboard on focus. Always follow
  `inputText` with `- hideKeyboard` if your next step targets a
  bottom-of-screen element.
EOF
  echo
  echo "_Total findings: $flag_count flagged out of $(printf '%s' "$results" | wc -l) testIDs_"
fi

if [ "$strict" -eq 1 ] && [ "$flag_count" -gt 0 ]; then
  exit 1
fi
